export const SYSTEM = {
  ADMIN_HOLDER_ID: 'Human (Admin)',
  DEFAULT_SYSTEM_PROMPT: 'You are a helpful AI traffic controller.',
  DEFAULT_AGENT_MODEL: 'LEX-ATC-Core',
} as const;

export const EVENT_TYPES = {
  LOCK_ACQUIRED: 'LOCK_ACQUIRED',
  LOCK_RELEASED: 'LOCK_RELEASED',
  SHARD_EPOCH_BUMP: 'SHARD_EPOCH_BUMP',
  AGENT_SPAWNED: 'AGENT_SPAWNED',
  AGENT_TERMINATED: 'AGENT_TERMINATED',
  PROPOSAL_CREATED: 'PROPOSAL_CREATED',
  PROPOSAL_APPROVED: 'PROPOSAL_APPROVED',
  PROPOSAL_EXECUTED: 'PROPOSAL_EXECUTED',
  PROPOSAL_CANCELLED: 'PROPOSAL_CANCELLED',
  SETTLEMENT_CREATED: 'SETTLEMENT_CREATED',
  DISPUTE_OPENED: 'DISPUTE_OPENED',
  DISPUTE_RESOLVED: 'DISPUTE_RESOLVED',
} as const;

